Feature/update types backend boubest 504
mimir-org/mimir pull request #308
Opened 2023-11-14 14:09 UTC by AndyEPandy

Updated data types to match Tyle

2023-11-15 08:38 UTC, AndyEPandy commented on src/service/ModelBuilder.Api/ModelBuilder.Api.csproj
> +    <UserSecretsId>600c472a-d748-4f46-bc8c-f5d5fde40a27</UserSecretsId>
Denne skal ikke være med. Generert ved å åpne local secrets (ikke brukt)

2023-11-15 09:05 UTC, jorgen-norheim requested changes
Noe smårusk, ellers very good. :)

2023-11-15 09:05 UTC, ghost commented on src/service/ModelBuilder.Api/ModelBuilder.Api.csproj
> +    <UserSecretsId>600c472a-d748-4f46-bc8c-f5d5fde40a27</UserSecretsId>
Skal fjernes

2023-11-15 09:05 UTC, ghost commented on src/service/ModelBuilder.Core/Profiles/LockProfile.cs
> +        CreateMap<LockRequest, LockDm>()
Her heter det fremdeles LockDm, skal det det?

2023-11-15 09:05 UTC, ghost commented on src/service/ModelBuilder.Models/Configurations/TerminalConfiguratio.cs
Skrivefeil i filnavnet her.

2023-11-15 09:05 UTC, ghost commented on src/service/ModelBuilder.Models/Data/AttributeType.cs
Blir attribute type rett her? Er ikke dette snakk om en instansiert attributt, for eksempel på en blokk?

2023-11-15 09:05 UTC, ghost commented on src/service/ModelBuilder.Models/Data/ImfType.cs
Også her usikker på om det blir rett å bruke "type" begrepet

2023-11-15 09:05 UTC, ghost commented on src/service/ModelBuilder.Models/Enums/RelationType.cs
> +    [Display(Name = "FulfilledBy")]
Feil display name

2023-11-22 09:26 UTC, AndyEPandy commented on src/service/ModelBuilder.Api/ModelBuilder.Api.csproj
> +    <UserSecretsId>600c472a-d748-4f46-bc8c-f5d5fde40a27</UserSecretsId>
Fjernet

2023-11-22 09:26 UTC, AndyEPandy commented on src/service/ModelBuilder.Api/ModelBuilder.Api.csproj
> +    <UserSecretsId>600c472a-d748-4f46-bc8c-f5d5fde40a27</UserSecretsId>
Ja den skal fjernes

2023-11-22 09:28 UTC, AndyEPandy commented on src/service/ModelBuilder.Core/Profiles/LockProfile.cs
> +        CreateMap<LockRequest, LockDm>()
Godt sett. Nei den skal oppdateres også.

2023-11-22 09:28 UTC, AndyEPandy commented on src/service/ModelBuilder.Models/Configurations/TerminalConfiguratio.cs
Fiksa

2023-11-22 09:32 UTC, AndyEPandy commented on src/service/ModelBuilder.Models/Data/AttributeType.cs
Jo, attribute type har heller ingen refereanser så jeg fjerner den. Har ingenting i Mimir å gjøre i denne sammenhengen.

2023-11-22 09:32 UTC, AndyEPandy commented on src/service/ModelBuilder.Models/Data/ImfType.cs
Fjernet "Type" begrepet

2023-11-22 09:33 UTC, AndyEPandy commented on src/service/ModelBuilder.Models/Enums/RelationType.cs
> +    [Display(Name = "FulfilledBy")]
Fikset

2023-11-22 09:40 UTC, jorgen-norheim approved these changes

2023-11-22 10:32 UTC, merged